rari/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  post 'sessions/create' => 'sessions#create', :as => 'sessions'

  get 'sessions/destroy'

  get 'page/index'

  get 'page/about'

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'

  resources :cars
  resources :users

  root 'page#index'

end

rari/app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :model, :year, :price, :image
  validates_numericality_of :year, :price
end

rari/app/models/user.rb
class User < ActiveRecord::Base
  has_many :cars
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :on => :create
  validates_presence_of :name, :on => :create
  has_secure_password

  #returns the formatted date of when the user joined
  def birthday
    return self.created_at.strftime('%b %-d %Y')
  end

end

rari/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user != nil
  end

  helper_method :current_user, :logged_in?
end

rari/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  require 'will_paginate'

  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all

    if params[:query]
      @cars = @cars.where("LOWER(model) LIKE ? OR price LIKE ? OR year LIKE ?", "%" + params[:query].downcase + "%", "%" + params[:query].downcase + "%", "%" + params[:query].downcase + "%")
    end

    #filtering
    case params[:filter]
    when 'az'
      @cars = @cars.order(:model)
    when 'za'
      @cars = @cars.order(:model).reverse_order
    when 'old'
      @cars = @cars.order(:year)
    when 'new'
      @cars = @cars.order(:year).reverse_order
    when 'low'
      @cars = @cars.order(:price)
    when 'high'
      @cars = @cars.order(:price).reverse_order
    end

    @cars = @cars.paginate(:page => params[:page], :per_page => 4)
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
    
    unless logged_in?
      redirect_to :back, notice: 'Please sign up to list a car!'
    end
  end

  # GET /cars/1/edit
  def edit 
    unless logged_in? && @car.user_id == current_user.id
      redirect_to request.env['HTTP_REFERER'] || root_url , notice: 'You can only edit your own listings!'
    end
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
    @car.user_id = current_user.id

    @car.image = upload 

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :year, :price, :desc, :image)
    end

    def upload
      uploaded_io = params[:car][:image]
      File.open(Rails.root.join('app', 'assets', 'images', 'uploads', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
      end
      return uploaded_io.original_filename
    end
end

rari/app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def about
  end
end

rari/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def new
  end

  def create
      user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_url, :notice => "Logged in!"
      else
        flash.now[:alert] = "Invalid email or password"
        render "new"
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

rari/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.cars.each do |car|
      car.destroy
    end

    @user.destroy

    respond_to do |format|
      format.html { redirect_to :logout, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :password_digest)
    end
end

rari/app/helpers/application_helper.rb
module ApplicationHelper
end

rari/app/helpers/cars_helper.rb
module CarsHelper
  def is_active?(filter)
    return false unless params[:filter]
    return filter == params[:filter]
  end
end

rari/app/helpers/page_helper.rb
module PageHelper
end

rari/app/helpers/sessions_helper.rb
module SessionsHelper
end

rari/app/helpers/users_helper.rb
module UsersHelper
end

rari/app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :desc %><br/>
    <%= f.text_area :desc, :cols => '40', :rows => '10' %>
  </div>
  <div class="field">
    <%= f.label :image %><br/>
    <%= f.file_field :image %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rari/app/views/cars/edit.html.erb
<section id='edit'>
  <h1>Edit Listing</h1>

  <%= render 'form' %>

  <%= link_to 'Back', :back %>
</section>

rari/app/views/cars/index.html.erb
<section id="list">

  <header>
      <h1>'Raris on the Market</h1>
      <nav id='filter'>
        <%= link_to "A-Z", cars_path(request.params.merge(:filter => 'az')), id: 'az', class: (is_active?('az'))? 'selected' : "" %> 
        <%= link_to "Z-A", cars_path(request.params.merge(:filter => 'za')), id: 'za', class: (is_active?('za'))? 'selected' : ""  %>
        <%= link_to "Newest", cars_path(request.params.merge(:filter => 'new')), id: 'new', class: (is_active?('new'))? 'selected' : ""  %> 
        <%= link_to "Oldest", cars_path(request.params.merge(:filter => 'old')), id: 'old', class: (is_active?('old'))? 'selected' : ""  %> 
        <%= link_to "Highest Price", cars_path(request.params.merge(:filter => 'high')), id: 'high', class: (is_active?('high'))? 'selected' : ""  %> 
        <%= link_to "Lowest Price", cars_path(request.params.merge(:filter => 'low')), id: 'low', class: (is_active?('low'))? 'selected' : ""  %> 
      </nav>
      <%= form_tag(cars_path, method: "get", id: "search_form") do %>
        <%= label_tag(:query, "Search:") %>
        <%= text_field_tag(:query) %>
        <%= submit_tag("Search", :name => nil) %>
      <% end %>
  </header>

  <% @cars.each do |car| %>
    <section class="car">
      <%= image_tag('uploads/' + car.image, class: 'car_image') %>
      <p class='car_model'><%= car.model %></p>
      <p class='car_year'><%= car.year %></p>
      <p class='car_price'><%= number_to_currency(car.price) %></p>
      <%= link_to("View", car_path(car), class: "car_view") %> 
      <% if logged_in? && car.user_id && current_user.id == car.user_id %>
        <%= link_to("Edit", edit_car_path(car), class: "car_edit") %>
      <% end %>
    </section>
  <% end %>

  <footer>
    <%= will_paginate @cars %>
  </footer>

</section>

rari/app/views/cars/new.html.erb
<section id='edit'>
  <h1>New Listing</h1>

  <%= render 'form' %>
</section>

rari/app/views/cars/show.html.erb
<section id='car_show'>
  <%= image_tag('uploads/' + @car.image, id: 'car_image') %>

  <h1><%= @car.model %></h1>

  <h2><%= @car.year %></h2>

  <h3><%= number_to_currency(@car.price) %></h3>

  <p><%= @car.desc %></p>

  <footer>Contact: <%= User.find(@car.user_id).name %> =&gt; <%= User.find(@car.user_id).email %></footer>
  <% if logged_in? && @car.user_id && current_user.id == @car.user_id %>
    <%= link_to 'Edit', edit_car_path(@car), id: 'edit_link' %>
    <%= link_to 'Delete Listing', car_path(@car), data: { :confirm => 'Are you sure?'}, :method => 'delete', :id => 'delete_link' %>
  <% end %>

  <%= link_to 'Back', :back , id: 'back_link'%>
</section>

rari/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rari</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>

  <header id='top'>
    <h1 id='logo'>Rari</h1>
    <p id='motto'>find your new 'Rari today (or Honda Civic)</p>
    <footer id='author'>created by: Jeremy Bassi</footer>
    <%= logged_in? ? link_to("Log Out", :logout, id: "log")  : link_to("Log In", :login, id: "log") %>
    <% unless logged_in? %>
    <% end %>
  </header>

  <nav id='side'>
    <% if logged_in? %>
      <%= link_to(current_user, id: "user") do %>
        <section id='user_info'>
          <h1 id="user_name"><%= current_user.name %></h1>
          <p id="user_cars">Cars: <strong><%= current_user.cars ? current_user.cars.count : 0 %></strong></p>
          <p id="user_birthday_label"><strong> Member since:</strong></p>
          <p id="user_birthday"><%= current_user.birthday %></p>
          <%= link_to("Log Out", :logout, id: "log") %>
        </section>
      <% end %>
    <% else %>
      <%= image_tag("ferrari.png", width: "8%", id: 'logo_img')%>
      <%= link_to("Sign Up!", :signup, id: "signup") %>
      <%= link_to("Log In", :login, id: "log") %>
    <% end %>

    <%= link_to("Home", page_index_path, class: "nav_link", id: "home_link") %>
    <%= link_to("About", page_about_path, class: "nav_link", id: "about_link") %>
    <%= link_to("All Cars", cars_path, class: "nav_link", id: "cars_link") %>
    <%= link_to("List a Car", new_car_path, class: "nav_link", id: "new_car_link") %>
    <%= link_to("See Users", users_path, class: "nav_link", id: "users_link") %>
    <% if logged_in? %>
      <%= link_to("View Profile", user_path(current_user), class: "nav_link", id: "show_user_link") %>
      <%= link_to("Edit Profile", edit_user_path(current_user), class: "nav_link", id: "edit_user_link") %>
    <% end %>

  </nav>

  <% if notice %>
    <div id='notice_area'>
      <p id='notice'><%= notice %></p>
    </div>
  <% end %>

  <section id='content'>
    <%= yield %>
  </section>

</body>
</html>

rari/app/views/page/about.html.erb
<section id="about">
  <h1>About Rari</h1>
  <h2>A Ruby on Rails App by Jeremy Bassi</h2>

  <p>Rari is all about living the life that you dream of, whether that means lane
  swerving in your 'rari even if it cost you about 230 bills, or picking up your 
  kids from soccer practice in a disgusting minivan.</p>

  <footer><strong>"Keep it Trill"</strong> - Jeremy</footer>

  <aside>Thingee Corporation</aside>

  <%= link_to image_tag("home.png", width: "10%"), page_index_path %>
</section>

rari/app/views/page/index.html.erb
<section id="homepage">
  <h1>Welcome to Rari</h1>
  
  <p>On Rari you can see a listing of cars put up for sale by their owners, along with their prices. Also, you can list your own car and try to sell it right on Rari. Bring home a brand new Enzo Ferrari today!</p>

  <%= image_tag("enzo.jpg") %>

  <nav id="menu">
    <ul>
      <li><%= link_to "Show me the cars!", cars_path %></li>
      <li><%= link_to "List a car", new_car_path %></li>
      <li><%= link_to "About Rari", page_about_path %></li>
    </ul>
  </nav>

</section>

rari/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rari/app/views/users/edit.html.erb
<section id='user_edit'>
  <h1>Edit Profile</h1>

  <%= render 'form' %>

  <%= link_to 'Back', :back %>
</section>

rari/app/views/users/index.html.erb
<section id='users_list'>
  <header>
    <h1>Rari Users</h1>
  </header>

  <% @users.each do |user| %>
    <%= link_to user_path(user) do %>
      <section class='user'>
        <p id='user_name'><%= user.name %></p>
        <p id='user_email'><%= user.email %></p>
        <p id='user_number'>Listings: <%= user.cars ? user.cars.count : 0 %></p>
      </section>
    <% end %>
  <% end %>
</section>

rari/app/views/users/new.html.erb
<section id='user_edit'>
  <h1>Sign Up!</h1>

  <%= render 'form' %>

  <%= link_to 'Back', :back %>
</section>

rari/app/views/users/show.html.erb
<section id='user_show'>
  <header>
    <h1><%= @user.name %></h1>
    <h2><%= @user.email %></h2>
  </header>

  <% if @user.cars %>
  <section id='user_cars'>
    <% @user.cars.each do |car| %> 
      <%= link_to car_path(car)  do %>
        <%= image_tag('uploads/' + car.image, class: 'car_thumb') %>
      <% end %>
    <% end %>
  </section>
  <% end %>

  <footer>
    <% if logged_in? && current_user.id == @user.id %>
      <%= link_to 'Edit', edit_user_path(@user) %>
    <% end %>
    <%= link_to 'Back', users_path %>
    <% if logged_in? && current_user.id == @user.id %>
      <%= link_to 'Delete Account', current_user, :method => 'delete', data: {confirm: 'Are you sure? All listings will be deleted as well.'}, id: 'delete' %>
    <% end %>
  </footer>
</section>